### ISSUE TITLE
Add cypress tests

### ISSUE THREAD

**Issue by circlecube** [newfold-labs/wp-module-onboarding#296]
Tests from the bluehost plugin that test components from this module should be added to this module.

More tests should be written to verify that the components properly render in the plugin and function. These should be universal tests that can pass no matter which brand plugin runs them. Use cypress environment variables to enable this.

Refer to this task for more information: https://github.com/bluehost/bluehost-wordpress-plugin/issues/594

**Comment by circlecube** [comment]
All these tests can be migrated into the module and will continue to run at the plugin level. These should be updated though to be brand agnostic - as they will run in each plugin that includes the module.

**Comment by arunshenoy99** [comment]
https://github.com/bluehost/bluehost-wordpress-plugin/pull/645
